"""add columns to table

Revision ID: 5f2147d4f493
Revises: 1f536d8b9502
Create Date: 2024-08-04 23:07:40.241436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2147d4f493'
down_revision = '1f536d8b9502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('image', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
